// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASa1kXnxeqFY6G8bvq_t3lch1jTCtrFcY',
    appId: '1:836052902454:web:26e6b64a277374fa4a6e97',
    messagingSenderId: '836052902454',
    projectId: 'innovestage',
    authDomain: 'innovestage.firebaseapp.com',
    storageBucket: 'innovestage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-EcborHcJ3kUyFjqMlW_0vlqRc8D-rGo',
    appId: '1:836052902454:android:ffe95a20e38817d84a6e97',
    messagingSenderId: '836052902454',
    projectId: 'innovestage',
    storageBucket: 'innovestage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKmBXi4CYqMnGTjUOGTvs2XCWzV6lXOWM',
    appId: '1:836052902454:ios:643333de6657b9fd4a6e97',
    messagingSenderId: '836052902454',
    projectId: 'innovestage',
    storageBucket: 'innovestage.appspot.com',
    iosBundleId: 'kz.app.innovestage',
  );
}
